title: 'The IronWerkz'
url: ironwerkz.github.io


# Optional but recommended
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme plugin

header_pages:
  - index.md
  - articles.md
  - about.md

style: dark # dark (default), light, hacker, or nord


#Build Settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
